steps:

  # Building
  - id: build-builder
    name: gcr.io/cloud-builders/docker
    args: ['build', '--rm=false', '-t', 'gcr.io/$PROJECT_ID/ice-cream-sales', '-f', 'Dockerfile.builder', '.']

  # Linting
  - id: lint
    name: gcr.io/$PROJECT_ID/ice-cream-sales
    args: ['./src/test.py']
    entrypoint: 'pylint'
    waitFor:
      - build-builder
